version: '3.8'

services:
  php:
    image: php:8.0-fpm
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network

  web:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - php

networks:
  app-network:
    driver: bridge
